<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
</head>

<body style="font-family: Arial, sans-serif; background: #f4f4f4; padding: 20px;">

    <div style="max-width: 600px; margin: 0 auto; background: #fff; border-radius: 8px; overflow: hidden;">
        <div style="background: #9F1D35; padding: 20px; text-align: center;">
            <h2 style="color: #fff; margin: 0;">Redeem Notification</h2>
        </div>
        <div style="padding: 24px;">
            <p>A voucher has been redeemed by a customer. Details below:</p>
            <p style="margin-bottom:10px; font-weight:bold; color:#333;">
                Voucher Information
            </p>
            <table style="width:100%; border-collapse:collapse; margin-bottom:24px;">
                <tr>
                    <td style="padding:8px; border-bottom:1px solid #eee; color:#666; width:35%;">
                        Item
                    </td>
                    <td style="padding:8px; border-bottom:1px solid #eee; font-weight:bold;">
                        <?php echo htmlspecialchars($itemname ?? '-', ENT_QUOTES, 'UTF-8'); ?>
                        <?php if (isset($description) && $description <> '') {
                            echo "(" . htmlspecialchars($description ?? '', ENT_QUOTES, 'UTF-8') . ")";
                        }
                        ?>
                    </td>
                </tr>
                <tr>
                    <td style="padding:8px; color:#666;">
                        Voucher
                    </td>
                    <td style="padding:8px; font-weight:bold;">
                        <?php echo htmlspecialchars($voucher_code ?? '-', ENT_QUOTES, 'UTF-8'); ?>
                    </td>
                </tr>
            </table>
            <p style="margin-bottom:10px; font-weight:bold; color:#333;">
                Customer Information
            </p>
            <table style="width:100%; border-collapse:collapse; margin:0;">
                <tr>
                    <td style="padding:8px; border-bottom:1px solid #eee; color:#666; width:35%;">
                        Customer
                    </td>
                    <td style="padding:8px; border-bottom:1px solid #eee; font-weight:bold;">
                        <?php echo htmlspecialchars($custname ?? '-', ENT_QUOTES, 'UTF-8'); ?>
                    </td>
                </tr>
                <tr>
                    <td style="padding:8px; border-bottom:1px solid #eee; color:#666;">
                        Phone
                    </td>
                    <td style="padding:8px; border-bottom:1px solid #eee; font-weight:bold;">
                        <?php echo htmlspecialchars($phone_number ?? '-', ENT_QUOTES, 'UTF-8'); ?>
                    </td>
                </tr>
                <tr>
                    <td style="padding:8px; border-bottom:1px solid #eee; color:#666;">
                        Email
                    </td>
                    <td style="padding:8px; border-bottom:1px solid #eee; font-weight:bold;">
                        <?php echo htmlspecialchars($customer_email ?? '-', ENT_QUOTES, 'UTF-8'); ?>
                    </td>
                </tr>
                <tr>
                    <td style="padding:8px; border-bottom:1px solid #eee; color:#666;">
                        Redeemed Date
                    </td>
                    <td style="padding:8px; border-bottom:1px solid #eee; font-weight:bold;">
                        <?php echo htmlspecialchars($redeemed_date ?? '-', ENT_QUOTES, 'UTF-8'); ?>
                    </td>
                </tr>
            </table>
            <p style="color: #999; font-size: 12px;">
                Please login to the system to process this redeem. This email was automatically generated by system. Please do not reply to this email.
            </p>
        </div>
    </div>
</body>

</html>